### ISSUE TITLE
Question: Merging Files

### ISSUE THREAD

**Issue by Kristoffeh** [ProgTrade/nUpdate#100]
Hello.

I have a question regarding files when the application is being updated. I have 2 json files.
1) Connection.json - contains information like ip, port and won't ever need to be changed.
2) Contains a list of ID's and other values. These can be changed at any time by the user. Let's call it id.json.

When the application is compiled, id.json is extracted to the output location along with everything else. And its default values will be set.
When nUpdate is initializing an update, is it possible to compare the 2 json files with the same name, and move over certain values if some are missing in the new file?

Lets say I've added a new variable to id.json, the old one doesn't have it but the new one does. Is it possible to get that value into the id.json after an update?

I've used nUpdate in the past and its a great AutoUpdater. Though I wasn't sure if this was possible for this sort of thing.

**Comment by dbforge** [comment]
Hi, there is no direct operation for that, but you can do this by writing a script in the "Execute code" operation that does this for you. The only problem is that there is currently no way to create custom files on the file system with specified contents. So you would need to put this file in a specific subfolder, e.g. `update_data`, let nUpdate extract it and then add the code operation that reads the new file from this subdirectory in your application's folder, compares it to the existing `id.json` file and merges them together.

Delta patching as default will be implemented in the future.

**Comment by Kristoffeh** [comment]
Thank you, I will implement nUpdate in my project and give it a try. I appreciate that you're still keeping this project up to date. Great work!

**Comment by Kristoffeh** [comment]
On another note: I've implemented nUpdate to my project, and have downloaded the Adminsitration tool to set it up.
I've successfully given it access to the FTP. It was able to create the updates.json but fails to write to it.

I am currently using a InfinityFree to host the file on a website. This may not be the best place to ask, but its worth a try. Its been a headscratcher so far.

The error message:
HTTP(S)-access of configuration file failed.
The configuration file was found on the FTP-server but it couldn't be accessed via HTTP(S). Unexpected character encountered while parsing value: <. Path ", line 0, position 0.

I've tried changing the permissions through Filezilla, but that didn't do much. Also couldn't find much information about this in the readme.md or wiki here on github. 

Last time i used nUpdate i was doing all of this through a VPS, this time i don't have access to the Apache configs. Hopefully we can sort this out.

**Comment by dbforge** [comment]
I am doing my best, but I don't work on this too much in my free time, unfortunately.

That's pretty annoying. So the message says that the file can be created, but the HTTP-GET request fails. Is the file empty or does it have some content? Reading `<` seems a bit odd to me. Probably this is because the server returns some config or predefined response in XML-format or anything. Can you access the file regularly in the browser?

**Comment by Kristoffeh** [comment]
I am baffled by your quick replies!

The updates.json is completely empty. Yes, I am able to access it through the webpage.
I've decided to test out another webhost, I have a strong feeling it has something to do with the HTTP Authentication. That is not set up for the nUpdate project, as i don't really know (or remember) what to put there.

**Comment by dbforge** [comment]
The file is always empty after first creation, so that is normal. Probably the response from the server is just incorrect.

The HTTP Authentication fields provide a way to specify BasicAuth credentials. Unless you have them set up, you can leave those empty.

The error message contains a bit too less information, unfortunately. It should show the complete server response or log it at least to see what the server responds with. If you tried another host, let me know.

**Comment by Kristoffeh** [comment]
Hi.

I moved to another webhost, and now i am able to upload packages via nUpdate, I've gotten further this time but i am getting an error when I am in my application and it is attempting to update.

See image, that's what it looks like before updating. 
![image](https://user-images.githubusercontent.com/10790999/154896683-28e4d779-46c4-4cf9-8504-c413ff96088a.png)

Error message: 
![image](https://user-images.githubusercontent.com/10790999/154896664-0bb6acbb-d15c-4277-9460-5e8834466ee6.png)

The error translates into:
Path may contain an empty string or just a space.

Where could this be exactly? I tried renaming my application to a name without any spaces. The link path where it is located does not have any spaces either.

EDIT: The application files are located at "C:\Users\Kriss\Desktop\v3"

**Comment by dbforge** [comment]
Hi,

can you maybe give me the full stracktrace by right clicking on the message and click "Copy entire message"?

**Comment by Kristoffeh** [comment]
Hi.

I ended up making an autoupdater from scratch, that way i could have full control of what's happening.
I'll close this issue as its no longer needed.

**Comment by TiToMoskito** [comment]
I ended up with the same problem. This is the full stacktrace:
System.ArgumentException: Der Pfad darf keine leere Zeichenfolge sein oder nur aus Leerzeichen bestehen.
   bei System.IO.Directory.CreateDirectory(String path)
   bei nUpdate.UpdateInstaller.Updater.CopyDirectoryRecursively(String sourceDirName, String destDirName)
