### ISSUE TITLE
Update window style issue

### ISSUE THREAD

**Issue by AndreasReitberger** [ProgTrade/nUpdate#102]
Since the latest update the UpgradeWindow looks like this on my end.

![image](https://user-images.githubusercontent.com/2952443/167285359-58ec0088-6821-4f26-8ef0-c471a3af2381.png)

It seems that it takes the background color from the main applications style.

![image](https://user-images.githubusercontent.com/2952443/167285379-e792b5c1-ae45-49c6-9210-45c37786e87c.png)

Is there a way to adjust the styles of the upgrade window?

**Comment by dbforge** [comment]
Oh, that is nasty. The WPF design was an external thing. @NoFear23m do you know about this one?
