### ISSUE TITLE
Errors uploading package, deleting package, checking configuration file

### ISSUE THREAD

**Issue by Berdi2** [ProgTrade/nUpdate#103]
This error comes up when I try to upload new packages:
![Screenshot(800)](https://user-images.githubusercontent.com/71555842/173247031-1caaac5d-54ae-48d6-9879-8c7fc09927cc.png)
(German translated: The length cannot be less than 0 (null).)
This didn't come up previously, I also can't delete that package anymore. Error:
![Screenshot(801)](https://user-images.githubusercontent.com/71555842/173247137-656fa27e-79ab-4ec1-89e2-cd480494489a.png)
(German translated: The length cannot be less than 0 (null).)
I think it might be connected to this error I get everytime I open up the project:
![Screenshot(799)](https://user-images.githubusercontent.com/71555842/173246967-53f5ca8e-9ce2-4751-9668-be7efbeacea5.png)
But I got this error from the first time opening the project and everything worked fine, so I thought it wouldn't be an issue.

I also haven't uploaded any packages to this project after 21st May 2021 (21.05.2021)

**Comment by dbforge** [comment]
Hi,

this is weird. Is your FTP configuration correct? The file seems to exists, but nUpdate does not seem to be able to locate it when using FTP. Does the FTP directory in any way differ from the real path?

**Comment by Berdi2** [comment]
So I think it does a little bit, the Update-URL is http://berdi.bplaced.net/Notes/ (I hope it's ok I write the website, it's not commercial in any way though) and the Directory is berdi.bplaced.net/www/Notes. I don't know why it adds the /www/ I think it's just a bplaced thing, but I don't know how FTP Servers work. However, the updates.json file is visible in the Directory in FileZilla and at the Update URL

Edit: I could imagine the subdomain being a problem

**Comment by dbforge** [comment]
Ah well, I remember someone also had a similar problem once. I think it was also bplaced.

So did you add the `www` to the directory in the project configuration? Maybe try to do so if it is missing or remove it in case it is there. If you are lucky, you may get it working by doing so. I do not know the structure of their file system, unfortunately.

Have you uploaded the file manually to the server or did the Administration do this?

**Comment by Berdi2** [comment]
It is included and trying to remove it gives me this error:
![Screenshot(803)](https://user-images.githubusercontent.com/71555842/173388766-2cfe1f44-9f0f-46a2-9932-d6572d418d9b.png)

Do you mean the updates.json file? The Administration uploaded that

**Comment by dbforge** [comment]
Can you right click on the error message, click "Copy entire message" and paste it here?
I guess it's a problem in the FTP library, but just to be sure about that.

Ok, then this is indeed weird. This indicates that your FTP configuration is correct and something else is wrong here. But I would need to have a look at the stacktrace for that, if you may post it (with the way above).

**Comment by Berdi2** [comment]
https://pastebin.com/TEsaXHJx
I hope this helps

**Comment by dbforge** [comment]
Ok, that happened when you editted the project. Can you maybe send me the above one from the package creation?

**Comment by Berdi2** [comment]
https://pastebin.com/BpdcJD8U
Edit: The package gets created, but cannot be released

**Comment by dbforge** [comment]
Okay, thank you. As I expected, this is a problem in the FTP library. It seems to get a response it can not parse/handle correctly.
All I can do is change the underlying FTP-library in this case.

**Comment by Berdi2** [comment]
That would be really nice!
Thank you for taking the time to even look into the issue :D
Edit: If you need any more data I will happily provide it!

**Comment by dbforge** [comment]
No worries. How quick do you need this?

**Comment by Berdi2** [comment]
No pressure, I can wait.
I only use it once in a while to push my hobby project to a few friends.

**Comment by dbforge** [comment]
Okay, I will maybe have a look at it tonight. The big advantage is that I've written clean, capsulated code back in the time.

**Comment by Berdi2** [comment]
Hey I'm back home, did you make any progress?

**Comment by dbforge** [comment]
Hi mate,

sorry, I was on vacation last week and did not manage to look into it that evening.
I will do that now.

**Comment by Berdi2** [comment]
Have you changed anything? I can upload and delete packages again without any problems

**Comment by dbforge** [comment]
Hi,

no, I pushed some changes in a feature branch, but have not yet changed anything.
That is nice to hear, maybe some changes from bplaced? Could be that they had difficulties.

**Comment by Berdi2** [comment]
Possible, I'm just glad it works again!

**Comment by dbforge** [comment]
Ok, that is nice. I will still push the feature branch soon, but then I won't have to hurry.
