### ISSUE TITLE
Can I use this project in my c++ project?

### ISSUE THREAD

**Issue by Mythpwr** [ProgTrade/nUpdate#107]
Hi, Can i use this project in my c++ project? Even so, i do not know how to install it. I'll make a simple project that can be used by my friends. Even when he  uses... once i update  the project that he can reach the update. But I don't know how to do so. When i searched on the internet, I found this project. Could  you help me at this issue?

**Comment by dbforge** [comment]
Hi,

I am afraid this is not possible without large efforts. This project targets .NET only.
