### ISSUE TITLE
nUpdate Administration: Operations not responsive

### ISSUE THREAD

**Issue by gerricom** [ProgTrade/nUpdate#115]
When adding a new package, the nUpdate Administration 4.0.0 can perform various operations. Unfortunately non of them are doing anything. I can click them and nothing happens besides the entry getting selected. I guess there is some minor glitch?

![2023-08-17  114031](https://github.com/dbforge/nUpdate/assets/459469/7fb4fb0c-52ca-4752-9b82-f19ab916c27f)

**Comment by dbforge** [comment]
Hi, this is a UX issue (because back in the day, I did not really think about this further). You can drag&drop them to the left `Operations` entry and they will appear next to the "Replace file/folder" operation that is available by default.

**Comment by gerricom** [comment]
🤦 thx!
