### ISSUE TITLE
Operation "Replace file/folder" won't be shown at editing of an update

### ISSUE THREAD

**Issue by master-m1000** [ProgTrade/nUpdate#14]
If I edit an update the operation "Replace file/folder" won't be shown. Other operations are visible.

**Comment by ProgTrade** [comment]
This is no issue as this has been done in purpose. That will be implemented in the next bigger update.

**Comment by ProgTrade** [comment]
Update: See 766de5b9df0053029ef2e74321b4817dbd7890f8

**Comment by ProgTrade** [comment]
Included in the newest release. cb9740acd3cc9d1fed205cfd500333716dac879f
