### ISSUE TITLE
Storing Path in nUpdate-Project

### ISSUE THREAD

**Issue by AliveDevil** [ProgTrade/nUpdate#15]
After migrating my useraccount to "C:\Users\AliveDevil" and moving "nUpdate Administration" to "nUpdate.Administration" nUpdate throws a filenotfoundexception.
Cause: Every path is saved in the project file.

**Comment by ProgTrade** [comment]
I will change the management. Consecutively you will be able to view the package and perform specific actions that are possible, even if the file doesn't exist locally.

**Comment by stefan-baumann** [comment]
Yeah, relative file paths instead of absolute ones in the project file would be a great to have ;)

**Comment by ProgTrade** [comment]
This is a good idea, there were two possibilities for the implementation. Either the paths are saved absolutely and adjusted when changing the location of the nUpdate files, or relative paths are used and combined with the active files path. I used relative ones as this won't require redundant code and produce any possible errors.
The feature's already implemented and will be included in the coming update this weekend.
