### ISSUE TITLE
Change Update Location

### ISSUE THREAD

**Issue by AliveDevil** [ProgTrade/nUpdate#16]
After my user account migration I tried to open a single project. Everything is OK except: I cannot see ANY Update because every update is saved in %AppData%.
I would like you to change that behaviour:
Either let the user specify where to store update files, make ovious where update files are stored or use a more intuitive path (i.e. in the project file directory under updates).

**Comment by ProgTrade** [comment]
I will add the possibility to change the path where the package files are stored.
