### ISSUE TITLE
use it for different locations

### ISSUE THREAD

**Issue by furesoft** [ProgTrade/nUpdate#25]
hi,

i want to make a generic updater with your lib. is it possible to update apps from other locations?

**Comment by ProgTrade** [comment]
Hi,

sorry for my late response. I have been in Rome for a week.
What do you exactly mean with "from other locations"?

**Comment by ProgTrade** [comment]
Hi @furesoft,

is this question still up-to-date?
If not, please respond to this comment that I can close the issue.

Regards

**Comment by ProgTrade** [comment]
There were no further responses, so I think the question could be answered or became irrelevant.
