### ISSUE TITLE
Add Chinese as language

### ISSUE THREAD

**Issue by a359807859** [ProgTrade/nUpdate#28]
I hope to be able to support Chinese

**Comment by ProgTrade** [comment]
Hi,

I've also received your email. Are you a native Chinese speaker? In case you are, that would be great. You might be able to fork the current repository as there are already localization files available. Then you can add a Chinese JSON file to nUpdate and send a pull request.

Localization for nUpdate Administration and most of the other components (except the installer as this one is linked with the library itself) is not yet implemented, but will follow in Version 4.0 which is currently in development. I think that there will still pass some time until I might have implemented everything. I would notify you then, if you're still interested.

Best,
Dominic

**Comment by a359807859** [comment]
Yes, I am Chinese. I have added nUpdate to my project.I hope that nUpdate can do better and better, I do not know how to add Chinese. Can you help me?

**Comment by a359807859** [comment]
Maybe I understand what you mean, do you want me to add Chinese, and then upload the branch?

**Comment by ProgTrade** [comment]
Nice.

So, what you need to do:
Make a copy of [that](https://github.com/ProgTrade/nUpdate/blob/master/nUpdate/Core/Localization/en.json) file and name it "zh-CN.json" when it's Chinese from China. Otherwise, you'll have to look for the correct culture code according to Microsoft's table: https://msdn.microsoft.com/de-de/library/ee825488(v=cs.20).aspx
If the translations would be the same for multiple Chinese culture codes, you can also add all of the affected ones.

Now, inside the file, you can replace all the English strings with the chinese ones. This shouldn't be too hard. ;) Make sure to leave the argument brackets there. These are the curly brackets with the numbers inside. To get an orientation where to put them in your translation of each string, have a look at the English implementation to get an idea what it might be used for. If you're not sure, just ask me how it will be replaced.

The last step consists of changing [this](https://github.com/ProgTrade/nUpdate/blob/master/nUpdate/Core/Localization/LocalizationHelper.cs#L47) file in the marked line. You just have to add the added cultures to the collection.

Best,
Dominic

**Comment by a359807859** [comment]
[http://update.hyuan.org/1.png](url) replace all the English？

**Comment by ProgTrade** [comment]
Your link is giving me a 404.

**Comment by a359807859** [comment]
You need to copy this link, and then into the browser, github can not go directly

**Comment by ProgTrade** [comment]
Ah, you pasted it the false way. The URL is the part in the normal brackets.
Anyway, yes, you need to replace all of the strings with the Chinese translation.

**Comment by a359807859** [comment]
Ok, i know how to do it, thank you
Best wishes to you

**Comment by ProgTrade** [comment]
Thanks for you collaboration. Let me know when you are done by sending a pull request. :)

**Comment by a359807859** [comment]
![2](https://cloud.githubusercontent.com/assets/18465053/24465253/f5dcfdbc-14de-11e7-9f7b-9a617349256d.png)
Why is this place gray?

**Comment by a359807859** [comment]
Does this software support some updates? I mean only to update a few of these documents, can not download the entire package can do it?
I use the translation software, so you may see the more difficult

**Comment by ProgTrade** [comment]
I don't quite understand what you are trying to ask me. What updates are you speaking about and what do you mean?

**Comment by a359807859** [comment]
Now the update is updated once an entire package, right?

**Comment by ProgTrade** [comment]
I don't understand what you mean by "update is updated". Are you still talking about the localization?
If not, please open a new issue for your question.

**Comment by ProgTrade** [comment]
@a359807859 Have you already progressed with the translations?

**Comment by ProgTrade** [comment]
@a359807859 How is it going? Have you been able to maybe complete the translations, yet?

**Comment by a359807859** [comment]
I didn't translate him. I'm an indie game developer. I don't have much time to spend on it,sorry.

**Comment by selway** [comment]
@ProgTrade 
I have translated it. 
But you need to modify the following code to work properly, otherwise Chinese will be garbled。
```
File：nUpdate\Core\Serializer.cs
Class: Serializer
Method:public static T Deserialize<T>(Stream stream)
```
```C#
using (var reader = new StreamReader(stream))
```
Replaced with
```C#
using (var reader = new StreamReader(stream, System.Text.Encoding.Default))
```
This is localized json file.
```json
{
   "CancelButtonText":"取消",
   "ContinueButtonText":"继续",
   "InstallButtonText":"安装",
   "CloseButtonText":"关闭",
   "UpdateSearchDialogHeader":"检测更新...",
   "NewUpdateDialogMultipleUpdatesHeader":"{0} 条可用更新。",
   "NewUpdateDialogSingleUpdateHeader":"{0} 条有效更新。",
   "NewUpdateDialogInfoText":"可以下载新的更新 {0}。",
   "NewUpdateDialogAvailableVersionsText":"更新版本: {0}",
   "NewUpdateDialogCurrentVersionText":"当前版本: {0}",
   "NewUpdateDialogSizeText":"总大小: {0}",
   "NewUpdateDialogChangelogText":"更新日志:",
   "NewUpdateDialogAccessText":"访问:",
   "NewUpdateDialogRegistryAccessText":"注册",
   "NewUpdateDialogFilesAccessText":"文件系统",
   "NewUpdateDialogProcessesAccessText":"进度",
   "NewUpdateDialogServicesAccessText":"服务",
   "NoUpdateDialogHeader":"没有任何可用更新。",
   "NoUpdateDialogInfoText":"当前程序已是最新版本。",
   "UpdateDownloadDialogLoadingHeader":"正在下载更新...",
   "UpdateDownloadDialogLoadingInfo":"请稍候，正在下载更新文件...  ({0}%)",
   "InstallerExtractingFilesText":"\"提取文件...\"",
   "InstallerCopyingText":"\"复制 {0}...\"",
   "InstallerInitializingErrorCaption":"\"初始化安装时出错\"",
   "InstallerUpdatingErrorCaption":"\"更新时出错\"",
   "InstallerFileInUseError":"安装程序不能写入文件 '{0}' 因为其它进程正在使用此文件。 终止所有访问的所有应用程序，然后按一下再试一次 \"好\".",
   "FileRenamingOperationText":"\"重命名文件 \"{0}\" 为 \"{1}\"...\"",
   "FileDeletingOperationText":"\"删除文件 \"{0}\"...\"",
   "RegistrySubKeyCreateOperationText":"\"创建注册表项 \"{0}\"...\"",
   "RegistrySubKeyDeleteOperationText":"\"删除注册表项 \"{0}\"...\"",
   "RegistryNameValuePairSetValueOperationText":"\"设置注册表项 \"{0}\" 值为 \"{1}\"...\"",
   "RegistryNameValuePairDeleteValueOperationText":"\"删除名称-值对 \"{0}\"...\"",
   "ProcessStartOperationText":"\"启动进程 \"{0}\"...\"",
   "ProcessStopOperationText":"\"终止进程 \"{0}\"...\"",
   "ServiceStartOperationText":"\"启动服务 \"{0}\"...\"",
   "ServiceStopOperationText":"\"结束服务 \"{0}\"...\"",
   "UpdateSearchErrorCaption":"检测更新时出错。",
   "UnfulfilledRequirementErrorCaption":"丢失组件。",
   "UnfulfilledRequirementErrorText":"某些更新的安装不能完成，因为以下要求未完成:",
   "OperatingSystemText":"操作系统:",
   "DotNetFrameworkText":".NET Framework:",
   "RequiredVersionText":"需求版本:",
   "PackageValidityCheckErrorCaption":"检测更新包签名时出错。",
   "PackageNotFoundErrorText":"未找到更新包文件。",
   "InvalidSignatureErrorCaption":"无效的签名。",
   "SignatureNotMatchingErrorText":"更新程序将取消更新包的安装和永久删除它们。",
   "InvalidSignatureErrorText":"更新包的签名不是有效的RSA签名。",
   "SearchProcessRunningExceptionText":"检测更新进程已运行。",
   "DownloadingProcessRunningExceptionText":"更新下载进程已运行。",
   "NetworkConnectionExceptionText":"网络连接不可用。",
   "PackageSizeCalculationExceptionText":"由于出现了未知错误，无法计算包大小。可能包文件不存在。",
   "InvalidJsonExceptionText":"包含更新配置的文件不是有效的JSON文件和/或不能处理数据。",
   "StatisticsScriptExceptionText":"尝试为统计传输数据时出错。请把这个问题报告给程序的开发人员，以便使他们能够修复它。反馈地址: {0}",
   "PackageFileNotFoundExceptionText":"找不到版本 \"{0}\" 的更新包。",
   "MainFolderCreationExceptionText":"无法创建应用程序的主文件夹。{0}"
}
```

**Comment by ProgTrade** [comment]
Thanks. You may also create a pull request for these changes.

**Comment by selway** [comment]
@ProgTrade 
OK, I'll do it.
