### ISSUE TITLE
Load assembly version from nUpdateVersionAttribute in nUpdate Administration

### ISSUE THREAD

**Issue by ProgTrade** [ProgTrade/nUpdate#33]
The nUpdateVersionAttribute has been designed for external access to the assembly's current version, but is not used in the feature provided by nUpdate Administration. This should be changed as this is the only reason why the attribute had been introduced.
I think that there may have been a merge conflict or any other problem as I am pretty sure this had already been implemented some time ago.

**Comment by ProgTrade** [comment]
The nUpdateVersionAttribute has been designed for external access to the assembly's current version, but is not used in the feature provided by nUpdate Administration. This should be changed as this is the only reason why the attribute had been introduced.
I think that there may have been a merge conflict or any other problem as I am pretty sure this had already been implemented some time ago.

**Comment by KillTrot** [comment]
Hello there,

How is it looking with this?

Greetings

**Comment by ProgTrade** [comment]
Hi,

I'm sorry, I need to admit that I haven't touched this, yet. The upcoming week I'll have my oral exam in French and I'm completely busy at the moment.
In 10 days, I'll have finished with everything and then I will directly stick to these issues. I think you may be waiting for another feature in nUpdate itself (as discussed in the other issue), but as this one is associated with it, that's no problem.
Is it ok for you to wait another two weeks maybe? After I've passed my exam in French, I may have two days available for changing this, if you'd need it very fast, now.
I'm sorry to disappoint you again, but this is not my intention at all.

Best,
Dominic

**Comment by KillTrot** [comment]
Hi,

I just wanted to hear that you don't forgot it:P

Take your time, i'm fine atm and have exams for myself. Good luck!

Greez

**Comment by ProgTrade** [comment]
No, I'm really looking forward to working on nUpdate again. :D So, I definitely do not forget about the issues I have right here.
Alright, then good luck to you, too!

Best,
Dominic

**Comment by ProgTrade** [comment]
Invalid issue. I've just found that this is actually implemented correctly, but I looked for it in the wrong class.
Nevertheless, I found that there needs to be a inproved check on the `nUpdateVersionAttribute` when activating this feature.
