### ISSUE TITLE
App restarted as admin?

### ISSUE THREAD

**Issue by KillTrot** [ProgTrade/nUpdate#34]
Hello and sorry for asking questions again:P

In my software i use an app.manifest to force the program using admin rights (requestedExecutionLevel level="requireAdministrator")

Now my question; Does nUpdate restart the host program (my software) with admin rights, after an update?

Greetings
Cedric

**Comment by ProgTrade** [comment]
Hi,

no problem. That's what GitHub is for. ;)
The update installer has the same manifest to make sure that it is started with admin privileges after downloading the packages. The host applicatio itself will not be run as admin unless it has a manifest included which enables this automatically. So, the host application is started using a simple `Process.Start` without specifying anything else (except the update arguments set).

**Comment by KillTrot** [comment]
I would have to test that to look if there are troubles with it.
I just thought nUpdate starts the software without admin rights, because windows never ask me for privileges after updating.
I'll sleep now and write you again tomorrow, after i did some sort of testing.

Good night

**Comment by KillTrot** [comment]
Ok, i've tested it and it works without any trouble.

Sorry for not testing it myself before asking such question.

Have a nice day:)
