### ISSUE TITLE
How can I use it?

### ISSUE THREAD

**Issue by selway** [ProgTrade/nUpdate#35]
Hi,
I have cloned this project and read it, but I can not find any instruction manual. 
1. Does the Update Server require only one configuration file  "pdates.json"?
2. Does the file "https://www.nupdate.net/test/updates.json" was be moved to "https://www.nupdate.net/updates.json"?
3. Does .ZIP UpdatePackages only needs to be packaged updated file?

**Comment by ProgTrade** [comment]
Hi,

1. The main things that your server needs to support is HTTP(S) and FTP(S). nUpdate Administration will then automatically upload the necessary files (the update configuration and the packages as ZIP files) to your server.
2. The file at the specified URIs is just for test purpose, so you don't need to pay attention on it. It may be that I have moved it during some tests. 
3. Inside of the ZIP files, nUpdate Administration will store the files and directories provided by the update package.

Just use nUpdate Administration, as it will do everything for you (including signing the packages for safety).

**Comment by selway** [comment]
Thank you,
I used nUpdate Administration,  but I encountered a problem that it can't connect to my FTP server.
My FTP server is built using FileZilla, it can be connected in Windows Explorer and Chrome.

**Comment by ProgTrade** [comment]
What errors did you get?

**Comment by selway** [comment]
@ProgTrade 
Exception
Message: An error occurred while opening a connection to FTP destination ftp://127.0.0.1 on port 21.
StackTrance
```
   Method: Starksoft.Aspen.Ftps.FtpsBase.CreateCommandConn()
   Method: Starksoft.Aspen.Ftps.FtpsBase.OpenCommandConn()
   Method: Starksoft.Aspen.Ftps.FtpsClient.Open(String user, String password)
   Method nUpdate.Administration.Core.Ftp.Service.FtpTransferService.TestConnection() 
   File: E:\Projects\nUpdateFork\nUpdate.Administration\Core\Ftp\Service\FtpTransferService.cs:Line 264
   Method nUpdate.Administration.Core.FtpManager.TestConnection()  
   File: E:\Projects\nUpdateFork\nUpdate.Administration\Core\FtpManager.cs:Line 170
   Method: nUpdate.Administration.UI.Dialogs.NewProjectDialog.<InitializeProject>b__40_0()  
   File: E:\Projects\nUpdateFork\nUpdate.Administration\UI\Dialogs\NewProjectDialog.cs:Line 588
```
InnerException
Message: Don't know the host.
StackTrance:
```
   Method: System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)
   Method: Starksoft.Aspen.Ftps.FtpsBase.CreateCommandConn()
```

**Comment by ProgTrade** [comment]
That IP refers to localhost. Don't you use an online server instead?

**Comment by selway** [comment]
It worked!
The program is that I wrote a wrong 'FTP-Host'. It's just writing host name '127.0.0.1', but I was wrote 'ftp://127.0.0.1'.
Thanks

**Comment by ProgTrade** [comment]
Okay, that would have been my next idea. Nice to see the problem solved.
