### ISSUE TITLE
Invalid assembly found

### ISSUE THREAD

**Issue by Bankst** [ProgTrade/nUpdate#43]
When trying to use "Load version from assembly" in nUpdate Administration 3.2.0, I get an error:

Invalid assembly found.

Could not load file or assembly 'nUpdate.WithoutTap,
Version=3.2.0.0, Culture=neutral, PublicKeyToken=null' or one
of its dependencies. The system cannot find the file specified.

I have updated the nuGet package in my application to 3.2, but it just won't load the assembly.

**Comment by ProgTrade** [comment]
Hi,

I will check, if I can reproduce this issue later.

Best,
Dominic

**Comment by ProgTrade** [comment]
Hi,

sorry for my late response.
I could not reproduce the error with the current version. How does your ` bin` folder containing your assembly look like?

Best,
Dominic
