### ISSUE TITLE
How to rename or delete files?

### ISSUE THREAD

**Issue by Patvdlee** [ProgTrade/nUpdate#45]
How do I add an action to delete/rename a file or any other action? I can only add files to directories. 

And is there any blog/forum about this Updater I can check?

**Comment by ProgTrade** [comment]
Hi,

this can be done using the operations that every update package provides. Just select the "Operations" entry on the left and drag and drop an operation from the list onto "Operations". This will add it to your package. As the order of the operations may be important, you can move them by selecting one and pressing CTRL+Up/CTRL+Down. The operation on top will be executed first, the one at the bottom is the last one.

There is a German forum where you can find a tutorial: https://www.vb-paradise.de/index.php/Thread/112472-nUpdate-Tutorial/
You may want to use the language setting in the top menu to see an English version (or one in your language), but be aware that it might not be completely accurate. I actually planned to expand the wiki here on GitHub, but I've unfortunately not come that far, yet.

Best,
Dominic

**Comment by Patvdlee** [comment]
Hi Dominic,

 

Thanks for your quick reply.. and yes that works indeed.. it was not complete clear to me how you could add the other actions to the action list 😊

 

I want to make a backup of my main executable before I upgrade the file, in case this doesn’t work and the client can always go back to the old version. Is there a way to do that?

 

I see that I can indeed change the order of the actions, but the replace file/folder stays always on top.. is that correct?

 

I like this Updater and am trying to compile the sources, so I can add some things in there that I might need..

 

Thanks,

 

Patrick

 





Patrick van der Lee

Founder / CEO / 

Director of software development

 

Contact info:

+63 9 993 250 755

+63 9 162 453 537

Emergency Nr:

+63 2 948 64 75

 <http://www.wiseguys.tv/> www.wiseguys.tv

**Comment by ProgTrade** [comment]
Hi,

yes, that‘s indeed a bit unclear at the moment. I already plan to improve that and add hints on how it works.

Rollbacks are currently not implemented, sorry. But, in case anything goes wrong, there should not be any problem in most of the cases.
Also, the installer works quite well and I‘ve not hear of any major problems with it, yet. :)

The „Replace files/folders“ option is meant to stay there, yes. That should be no problem as it does not interfer with other operations.

Best,
Dominic
