### ISSUE TITLE
How does clients/users get the update?

### ISSUE THREAD

**Issue by damms005** [ProgTrade/nUpdate#46]
Very simple and basic question that I do not see attended to anywhere. The wikis, github issues, information on the official website, etc... all explain and discuss the administration end. 

How is nUpdate implemented on the client side, such that when we done updating and setting things up at the admin side, client/users of my app will have their nUpdate downloading as intended?

Thanks

**Comment by ProgTrade** [comment]
Hi,

you need to reference nUpdate in yout project. This may be done using NuGet as it‘s the easiest way.
Then checkout the „Copy source“ button in your project overview in nUpdate Administration. Simply paste the code into your method that should start the update process and add the following:

`new UpdaterUI(updateManager, SynchronizationContext.Current).ShowUserInterface();`
where `updateManager` refers to your instance that is created above.

This will start the complete update process using the integrated user interface. If you want to implement your own, check out the UpdateManager and rebuild the UpdaterUI class to see how this can be done.

Best,
Dominic
