### ISSUE TITLE
nUpdate.UpdateInstaller does not start the update process

### ISSUE THREAD

**Issue by selway** [ProgTrade/nUpdate#54]
Version: 3.3.0
No error or exception, it just stopped after `ShowDialog`.
 The `ShowDialog();` at line 36 in `MainForm.cs` will block the execution of `ThreadPool.QueueUserWorkItem(arg => RunUpdateAsync());` at line 141 in `Update.cs`.

**Comment by ProgTrade** [comment]
Does this error occur every time? I will check that out now.

**Comment by ProgTrade** [comment]
The line had been moved in a commit of the last update and I don't know why. Thanks for the hint. I will fix this immediately.
