### ISSUE TITLE
Double escape on CustomInstallerUiAssemblyPath prevents one from running an own installer assembly

### ISSUE THREAD

**Issue by swASO** [ProgTrade/nUpdate#55]
if you try it - you will get a error, too many arguments 

https://github.com/ProgTrade/nUpdate/blob/7d384aa5a68589587a5b3192dc47127f3c57626a/nUpdate.Shared/Updating/UpdateManager.cs#L399

https://github.com/ProgTrade/nUpdate/blob/7d384aa5a68589587a5b3192dc47127f3c57626a/nUpdate.Shared/Updating/UpdateManager.cs#L408

a quick fix would be great :)

**Comment by ProgTrade** [comment]
Thanks, I will get to that the day after tomorrow and fix it then with the release of the new version.
