### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by AliveDevil** [ProgTrade/nUpdate#6]
Following files are missing in the repository but are referenced in project files.
nUpdate:
Core\Operations\OperationsMethods.cs
Core\SizeConverter.cs
UI\Dialogs\BaseForm.cs
UI\Dialogs\BaseForm.resx

nUpdate Administration:
Core\Application\Sql.cs
Core\Update\Operations\OperationMethods.cs
Core\Update\Operations\Panels\RegistryEntryCreateOperationPanel.cs
Core\Update\Operations\Panels\RegistryEntryDeleteOperationPanel.cs
Core\Update\Operations\Panels\RegistryEntrySetValueOperationPanel.cs
UI\Controls\WatermarkTextBox.cs

nUpdate UpdateInstaller:
Controls\ControlPanel.cs
Core\Operations\OperationMethods.cs
Dialogs\MainForm.cs

**Comment by ProgTrade** [comment]
Problem fixed, thanks.
