### ISSUE TITLE
Error uploading new configuration file

### ISSUE THREAD

**Issue by Bykiev** [ProgTrade/nUpdate#66]
Hello, I've created an FTP-server running on IIS and I have a full access. On uploading new configuration file I'm getting this strange error (nUpdate Administration v3.3.1).
![error](https://user-images.githubusercontent.com/13969777/44414561-c08d2680-a576-11e8-854d-fba9cdeae1da.png)

**Comment by ProgTrade** [comment]
Hm, this is strange. Actually that should be a happy code, not an error. As nUpdate Administration uses Starksoft.Aspen, the error must lie there. I can look at the code lines and ask the library author where this may come from.

Best,
Dominic

**Comment by Bykiev** [comment]
@ProgTrade Thanks Dominic, I'll wait for your reply

**Comment by ProgTrade** [comment]
Could you please give me the whole stacktrace of the error? To do this, just rightclick on the error message and click "Copy entire message".
Then I will immediately open an issue.

**Comment by Bykiev** [comment]
@ProgTrade, it seems I've created a new project from scratch and now I'm getting this error (the "Copy entire message" menu item is inactive). Russianl text error in English: "Timeout expired"

![error2](https://user-images.githubusercontent.com/13969777/44418041-f2ef5180-a57f-11e8-88ca-b4c167811471.png)

**Comment by Bykiev** [comment]
@ProgTrade finally fixed the issue, it's because of my mistake in update url.
Thanks!

**Comment by ProgTrade** [comment]
Okay yes. That is what the message indicates. So with passive mode it does now work?

**Comment by Bykiev** [comment]
@ProgTrade Yes, I changed FTP mode to active by mistake, so when I recreated the project passive mode was selected by default and it's working now. 
Thanks for  your support!
