### ISSUE TITLE
Is there any documentation for this at all?

### ISSUE THREAD

**Issue by megakraken** [ProgTrade/nUpdate#67]
Hello,

Is there any documentation for this project at all? It looks nice from the screenshots but I can't find anything in the Wiki and the *docs* section on the Website is simply a listing of the types and namespaces.

Thank you!

**Comment by ProgTrade** [comment]
Hi,

there is not really any English documentation for nUpdate, yet. You can find a German tutorial here: https://www.vb-paradise.de/index.php/Thread/112472-nUpdate-Tutorial/
Maybe you can manage to translate the content. If not, you may also ask me everything via mail.

Best,
Dominic
