### ISSUE TITLE
Blur fonts in Windows 10 HDPI Administration v3.3.1

### ISSUE THREAD

**Issue by JavierCanon** [ProgTrade/nUpdate#70]
add an app.manifiest file for support hdpi 
https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms

**Comment by ProgTrade** [comment]
I've already tried this once but did not quite get it working. That's why I decided to keep it like that and rewrite everything WPF (where HDPI is no problem any longer).
Otherwise, if you could get this working, you could supply the feature via a pull request.

**Comment by ProgTrade** [comment]
As the article quotes this is only available for .NET 4.7. So not possible to this point.
