### ISSUE TITLE
nUpdate doesn't wait to install updates until app has closed

### ISSUE THREAD

**Issue by FlashDeviant** [ProgTrade/nUpdate#73]
Hi,

I want to use nUpdate to update my executable app on launch. Currently have set my instance of the UpdateManager to have a "CloseHostApplication" of "true". However when I run the InstallPackage routine, nUpdate will attempt to overwrite my executable before it's had a chance to close causing it to open a dialog saying the update couldn't be completed.

Is there a way to delay the update from starting for a few seconds to allow time for the app to close?

**Comment by ProgTrade** [comment]
Hi,

you do not need to set this property to `true` as it is the default value.
What kind of application are you running? Windows Forms, Console or WPF?

By default, nUpdate will call `Application.Exit` on your program once the installation process is started. May it be that you have some code in your program that prevents the closing of each form from happening?

Of course, it would be good to know your application type as WPF and console need a small workaround to get this working atm. For that the `TerminateApplication` method is marked as `virtual`. You may want to override it and kill your application the way that it needs to be done.

Best,
Dominic

**Comment by FlashDeviant** [comment]
I'm programming in WinForms currently.
The process I can see on screen once the InstallPackage method is called is that an error box pops up saying the executable is locked just as my application closes. This does all occur within the space of a second or so. I don't have any code overriding the shutdown of the app.

**Comment by ProgTrade** [comment]
Do you have any code in your application that keeps it running even if all forms are closed (e. g. NotifyIcon or any else running services)?

You may want to try creating a class that inherits from `UpdateManager` and override the `TerminateApplication` method to kill your process without any resting active resources.
Then use this `UpdateManager` subclass instead.

Best,
Dominic

**Comment by FlashDeviant** [comment]
Hi @ProgTrade, took a while to get back to you as I'm working on many things at once.

I was able to overcome this issue by shifting the updating code into my Program.cs before my first form can be initialized. It would have been desirable to have included this in my form so I can notify the user that the update is starting but that isn't a big deal as my use case will require all updates to be mandatory anyway and most only delay startup by a few more seconds by my testing.

Thanks for your help! 
Hope this assists anyone with a similar issue
