### ISSUE TITLE
Operations before the "Replace file/folder" module

### ISSUE THREAD

**Issue by Jacob-JA-Shanks** [ProgTrade/nUpdate#74]
Hi again,

I was wondering if it is possible to have an operation placed before the "Replace file/folder" operation.
For instance so I could stop a running Windows Service, replace the necessary files and restart it once completed?

I have tried CTRL+Up to push it above but this doesn't appear to be possible.

**Comment by ProgTrade** [comment]
Hi Jacob,

indeed the order is meant to replace files and folders first before executing the necessary operations.
But you are right, it may make sense to have an arbitrary order to ensure further possibilities like you've said e.g.

I will include this in an update which I will work on, now.

Best,
Dominic

**Comment by ProgTrade** [comment]
Feature include in the newest release. cb9740acd3cc9d1fed205cfd500333716dac879f

**Comment by Jacob-JA-Shanks** [comment]
Many thanks! I will give it a try 👍
