### ISSUE TITLE
Feature Request: Install as Admin

### ISSUE THREAD

**Issue by Pilzinsel64** [ProgTrade/nUpdate#76]
Hello!

Could you add a property that allow to disable starting the installer as admin, please?
Currently I inject a property into your dll using dnSpy.

And I use it like that:
![grafik](https://user-images.githubusercontent.com/23138465/60892470-75980280-a25f-11e9-97ca-80d879a2701a.png)

Thanks!

**Comment by ProgTrade** [comment]
Hi,

yes, I actually wanted to implement this in the last update, but I forgot it due to all the stuff with the secflaw.
I will have a look at this tomorrow. :)

Best,
Dominic

**Comment by Pilzinsel64** [comment]
Thank you very much! 👍

**Comment by ProgTrade** [comment]
Hi there,

how much do you need this at the moment? As I see you've got a solution for now.
Currently, I am pretty busy and it may take 2 weeks until I can really release a new version.

Best,
Dominic

**Comment by Pilzinsel64** [comment]
Hi,

no problem, I can understand you.
Yes, i found a solution that is working well but I have to repeat the stepts to enable for every update. So, i would be happy if you can implement it with the next update.

Thanks!

**Comment by ProgTrade** [comment]
Thanks. I will have a look at it the next weekend then.
