### ISSUE TITLE
Start arguments for host application

### ISSUE THREAD

**Issue by KillTrot** [ProgTrade/nUpdate#80]
Hello,

Is there a possibility to restart the host application with command line arguments?

I tried manager.arguments, but this does not seem to work.

Greetings-

**Comment by ProgTrade** [comment]
Hi,

the `UpdateArgument` class is used to provide the application with arguments when starting it again after the update installation.
The arguments are joined by a pipeline character (`|`) to make sure they can be splitted apart again.
As there is also a `Main`-function in a console application, the arguments should be passed to it when running the application. Or am I getting your intentions wrong?

Best,
Dominic

**Comment by KillTrot** [comment]
Ah alright, I'm splitting my command line parameters with "-", thus it doesn't recognize the ones you're adding.
Could you probably add an option for the delimiter?

**Comment by ProgTrade** [comment]
I may add that, yes.
For a current hack, you may check if the result of splitting with the dash is an empty array and then, split by `|` .

**Comment by KillTrot** [comment]
I'll try to do that, thanks
